# Generated by Django 4.0.3 on 2022-03-16 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=100)),
                ('required_value', models.IntegerField()),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_list.facilitytype')),
            ],
        ),
    ]
